Repository Uspacy/swagger, pull requests merged in 2022-10, with the labels that each got.

#4 Files Service docs have been added
  .gitignore
  schemas/api.yml
Labels: size/L

#5 added field description
  schemas/api.yml
Labels: size/S

#6 Add comment service documentation
  schemas/api.yml
Labels: size/L

#8 Update comment-service documentation
  schemas/api.yml
Labels: size/M

#7 Feature/t roles and permissions
  schemas/api.yml
Labels: size/XL

#9 added upload avatar
  schemas/api.yml
Labels: size/L

#10 added delegate method for tasks
  schemas/api.yml
Labels: size/M

#11 Email invitation
  schemas/api.yml
Labels: size/L

#12 Updates for newsfeed-service for comments removal
  schemas/api.yml
Labels: size/L
