Repository Uspacy/swagger, pull requests merged in 2023-05, with the labels that each got.

#61 Updated request body for post/patch methods
  schemas/api.yml
Labels: size/L

#62 [CU-865c750ry] feature: uspacy.dev page
  css/index.css
  images/facebook icon.svg
  images/instagram icon.svg
  images/linkedin icon.svg
  images/swagger-icon.svg
  images/telegram icon.svg
  images/twitter icon.svg
  images/uspacy-dev-logo.svg
  images/youtube icon.svg
  index.html
Labels: size/L

#63 [CU-865c750ry] hotfix: fix circle position
  css/index.css
Labels: size/XS

#65 hotfix: fix bug with scroll
  css/index.css
Labels: size/XS

#66 [CU-865c750ry] bugfix: circle position
  css/index.css
Labels: size/S

#67 feature: change title and description
  index.html
Labels: size/S

#68 method for getting related entities in crm
  schemas/api.yml
Labels: size/M
