Repository Uspacy/swagger, pull requests merged in 2023-04, with the labels that each got.

#53 Increase swagger ui version
  api.html
Labels: size/XS

#55 Fileimport swagger doc
  schemas/api.yml
  schemas/fileimport.yml
Labels: size/L

#54 [CU-865c3j16z] Added funnel_id filtering for deals
  schemas/api.yml
Labels: size/XS

#56 swagger fileimport fix
  schemas/api.yml
  schemas/fileimport.yml
Labels: size/L

#57 Minor name fix
  schemas/api.yml
Labels: size/XS

#58 Add base crm event call api
  schemas/api.yml
Labels: size/L

#59 Add post, get, patch app endpoints
  schemas/api.yml
Labels: size/L

#60 Extend crm service call events
  schemas/api.yml
Labels: size/M
