Repository Uspacy/swagger, pull requests merged in 2023-03, with the labels that each got.

#46 Group filter description
  schemas/api.yml
Labels: size/XS

#47 [CU-865bpey46] Update swagger about filters support
  schemas/api.yml
Labels: size/L

#48 [CU-865bujrx6] Add check join request endpoint, update existing endpoints
  schemas/api.yml
Labels: size/M

#50 Cu 865bu8pdy multifunnel
  schemas/api.yml
Labels: size/L

#51 task status management
  schemas/api.yml
Labels: size/L

#52 task status management
  schemas/api.yml
Labels: size/S
