Repository Uspacy/swagger, pull requests merged in 2023-02, with the labels that each got.

#38 Fix CRM tasks routes
  schemas/api.yml
Labels: size/XS

#39 [CU-862j47m6c] Add search service to api.yml
  schemas/api.yml
  schemas/search.yml
Labels: size/L

#40 role title
  schemas/api.yml
Labels: size/S

#41 [CU-865bt4chn] - Fix: Make logo properly updated while updating the ent…
  schemas/api.yml
Labels: size/M

#42 [CU-865bteaj2] - Create subtasks in Tasks-service
  schemas/api.yml
Labels: size/M

#43 CU-865bu4m3b - Make a filter for group listing to show only groups th…
  schemas/api.yml
Labels: size/XS

#44 [CU-865bujrx6] Add private group join endpoints
  schemas/api.yml
Labels: size/M

#45 crm
  schemas/api.yml
Labels: size/XL
