Repository Uspacy/swagger, pull requests merged in 2024-12, with the labels that each got.

#138 added query params to call events list schema
  schemas/api.yml
Labels: size/M

#82 Feature/1549 documents specifications
  schemas/api.yml
Labels: size/XXL

#140 OpenAPI fixes
  schemas/api.yml
Labels: size/S

#139 changed call events list begin time query parameter
  .gitignore
  schemas/api.yml
Labels: size/S

#141 Add incoming ad outgoing webhooks api
  api.html
  schemas/api.yml
Labels: size/XXL

#142 Publish email service api doc
  api.html
  schemas/api.yml
Labels: size/XXL

#143 Add security section for email service endpoints
  api.html
  schemas/api.yml
Labels: size/M
